lesson-2
DariaRomanowska/if-js pull request #2
Opened 2022-09-16 21:00 UTC by DariaRomanowska

2022-09-18 18:14 UTC, 5tronciy requested changes
Not all requirements are met. And try not to load the files that are not applied to the current task (lesson.js here).

2022-09-18 18:14 UTC, 5tronciy commented on main.js
> +console.log(test - 1); // 1 number
Wrong comment

2022-09-18 18:14 UTC, 5tronciy commented on main.js
> +user = student; //переопределены данные на 'Daria Ramanowska'
Write the comments on English only.

2022-09-18 18:14 UTC, 5tronciy commented on main.js
> +console.log(test === 3); //false
It doesn't assign with the task requirement. You should convert the value of variable `test` to a boolean.

2022-09-21 06:23 UTC, DariaRomanowska commented on main.js
> +console.log(test - 1); // 1 number
why?

2022-09-21 21:20 UTC, 5tronciy commented on main.js
> +console.log(test - 1); // 1 number
Oh, I didn't mention that you haven't changed the variable test. 
I think that it doesn't assign the task in this case. Make the necessary changes, please.

2022-09-21 21:39 UTC, 5tronciy requested changes
Be careful with the task.

2022-09-21 21:39 UTC, 5tronciy commented on main.js
> +let newTest = Boolean(false);
Where is the converting of variable `test`? This statement doesn't include it.

2022-09-21 21:39 UTC, 5tronciy commented on main.js
> +console.log(test + "1"); // '21' string
It is better to use a consistent style for the strings. I think prettier may solve it.

2022-09-21 21:39 UTC, 5tronciy commented on main.js
> +  if (i >= 5 && i <= 10) {
It doesn't assign the task now.

2022-09-23 16:32 UTC, 5tronciy requested changes
Need improvement.

2022-09-23 16:32 UTC, 5tronciy commented on main.js
> +test = Boolean(false);
Why false?
Look at previous operations with `test`. It should be similar.

2022-09-23 16:32 UTC, 5tronciy commented on main.js
> +
Don't push empty rows. Do you use prettier?

2022-09-28 21:13 UTC, 5tronciy requested changes
The task requirement is not done.

2022-09-28 21:13 UTC, 5tronciy commented on main.js
> +
The requirement of transforming 'test' to boolean type doesn't meet.

2022-10-05 19:31 UTC, 5tronciy requested changes
Transform variable 'test' to boolean type.

2022-10-05 19:31 UTC, 5tronciy commented on main.js
> +test = Boolean(test === 20);
What is the magic number 20 for here? Where did you get it?
It doesn't match the task.

2022-10-14 22:24 UTC, 5tronciy approved these changes
Bingo!
Approve.

2022-10-14 22:24 UTC, 5tronciy commented
After approval and only after it, you may merge PR yourself. Let me know if something goes wrong with it.

2022-10-23 12:46 UTC, merged